language: objective-c
osx_image: xcode9

script:
  - xcodebuild test -destination "platform=iOS Simulator,name=iPhone 7" -sdk iphonesimulator11.0 -project Travis-Demo/Travis-Demo.xcodeproj -scheme Travis-Demo CODE_SIGNING_REQUIRED=NO
